savannahghi/healthcrm

healthcrm.go, healthcrm_test.go, input.go, output.go
=> feat: fetch facilities

client.go, client_test.go, healthcrm.go, healthcrm_test.go, input.go
=> feat: update facility

healthcrm.go, healthcrm_test.go, output.go
=> feat: get facility services

healthcrm.go, healthcrm_test.go
- fetches all services if no facility is provided. Else, return the services associated with the provided facility
=> feat: fetch services offered in a facility

output.go
=> fix: return services when fetching facility(ies)

healthcrm.go, healthcrm_test.go, input.go
=> fix: add pagination when fetching services

healthcrm.go, healthcrm_test.go, input.go
- create service in health crm and link a facility to a certain service Extras:
- add pagination when listing facilities offering a certain service
=> feat: create service and link service to facility

client.go, healthcrm.go, healthcrm_test.go, input.go
=> feat: add get facilities method for retrieving facilities

healthcrm.go, healthcrm_test.go
=> chore: update method that gets services offered by all facilities

healthcrm.go, healthcrm_test.go
=> chore: allow searching facilities by service name

output.go
=> chore: update `Distance` type to float64

client.go, client_test.go, healthcrm.go, healthcrm_test.go
=> fix: enable get facilities by service ids

.gitignore, healthcrm.go, healthcrm_test.go, input.go, output.go
=> feat: definitive profile creation on healthcrm service

healthcrm.go, healthcrm_test.go, input.go, output.go
=> fix(CPL-312): fixt profile syncing input and output

enums.go, enums_test.go, input.go
=> feat: add contact and identifier types

healthcrm.go, healthcrm_test.go, input.go
=> fix: remove service code and add fields to identifiers and contacts

input.go
=> fix: make valid from and valid to not to have default values

healthcrm.go, healthcrm_test.go, output.go
=> feat: add ability to fetch multiple services

healthcrm.go, healthcrm_test.go, output.go
=> feat: add multiple facilityIDs search

enums.go, enums_test.go
=> feat: add gender enums

enums.go
=> chore: fix unknown gender enum

healthcrm.go
=> chore: add error logging to profile creation

go.mod, go.sum, utils.go, utils_test.go
=> feat: add gender conversion from enumutils to healthCRM gender types

.github/workflows/ci.yaml, .golangci.yaml, client.go, client_test.go, healthcrm_test.go
=> feat: refactor CI

healthcrm_test.go, input.go
=> chore: make profileInput gender be an enum

healthcrm.go, healthcrm_test.go, output.go
=> feat: add fetching of identifiers by healthID

client.go, client_test.go, go.mod
=> feat: add a background goroutine to update access token

healthcrm_test.go, output.go
=> feat: add profile dto output to identifiers and contacts

go.mod, go.sum, healthcrm_test.go, output.go
=> fix: change time unmasharlling to date

enums.go
=> chore: add identifier types

healthcrm_test.go, input.go
=> fix: change valid to and valid from to date objects

enums.go, enums_test.go, healthcrm.go, healthcrm_test.go, input.go, output.go
=> feat: add profile matching

healthcrm.go, healthcrm_test.go, input.go, output.go
=> feat: add identity verification

.github/workflows/ci.yaml, .golangci.yaml, client.go, enums.go
1. Extended the IdentifierType enum with the following types:
- `DR_CHRONO_CHART_ID`
- `BIRTH_NOTIFICATION_NO`
- `SHA_NUMBER`
- `HOUSEHOLD_NUMBER`
- `TEMPORARY_ID`
- `TEMPORARY_DEPENDENT_ID`
2. Migrated golangci-lint to v2 from previous v1 version.
- Any new files …
=> feat: extend the enum types for IdentifierType

enums.go, healthcrm.go, healthcrm_test.go, output.go
=> feat(CPL-1814): implement practitioners category

output.go
=> fix(CPL-1835): fix Practitioner BusinessHours

output.go
=> chore: return facility photos from healthCRM

output.go
=> feat(CPL-1864): add slug to facility

healthcrm.go, input.go
=> Allow multiple ids

healthcrm.go
=> feat: add search query params
